### ISSUE TITLE
Flexible in string or function as parameter

### ISSUE THREAD

**Issue by junkew** [genius257/AutoIt-projects#5]
see post https://www.autoitscript.com/forum/topic/185720-autoitobject-pure-autoit/?do=findComment&comment=1393337

At certain places this has to be built in
$newMethod = IsFunc($newMethod) ? $newMethod : Execute($newMethod)

**Comment by genius257** [comment]
The project have moved to it's own repository and version 2.0.0 have this requested feature https://github.com/genius257/AutoItObject-Internal/releases/tag/2.0.0
